name: "RVC2MQTT"
description: "Addon to sniff can data in RVC format"
version: "1.0.0"
slug: "RVC2MQTT"
url: "https://github.com/spbrogan/rvc2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386