name: "RVC2MQTT"
description: "Addon to sniff can data in RVC format"
version: "1.0.0"
slug: "RVC2MQTT"
url: "https://github.com/spbrogan/rvc2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
init: false

options:

  interface_name: "can0"

  plugin_paths: "/"

  map: 
    - dgn: 1FFBD
      instance: 1
      group: '00000000'
      type: light
      instance_name: bedroom_light

    - dgn: 1FFBD
      instance: 2
      group: '00000000'
      type: light
      instance_name: main_light

    - dgn: 1FFBD
      instance: 8
      group: '00000000'
      type: light
      instance_name: awning_light

    - dgn: 1FF9C
      instance: 2
      type: temperature
      instance_name: bedroom_temp

    - dgn: 1FFB7
      instance: 0
      type: tank_level
      instance_name: fresh_water_tank

    - dgn: 1FFB7
      instance: 1
      type: tank_level
      instance_name: black_waste_tank

    - dgn: 1FFB7
      instance: 2
      type: tank_level
      instance_name: rear_gray_waste_tank

    - dgn: 1FFB7
      instance: 18
      type: tank_level
      instance_name: galley_gray_waste_tank

    - name: WATER_PUMP_STATUS
      type: water_pump
      instance_name: fresh water pump

    - name: WATERHEATER_STATUS
      type: waterheater
      instance: 1
      instance_name: trailer waterheater

    - name: DC_LOAD_STATUS
      type: tank_warmer
      instance: 34
      instance_name: waste tank heater

    - name: DC_LOAD_STATUS
      type: tank_warmer
      instance: 35
      instance_name: fresh water tank heater

    mqtt:
      - broker:   "100.64.39.110:9883"
        username: "rvc"
        password: "c0ugar"
  
schema:
  interface_name: str?
  plugin_paths: str?
  mqtt:
    - broker: str
      username: str
      password: str
  map:
    - dgn: str?
      instance: int?
      type: str?
      instance_name: str?
    - name: str?
      type: str?
      instance: int?
      instance_name: str?
