#
# define the name of the can device
#
interface:
  name: can0

#
# Logging info
# See https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
#
logger:
  version: 1
  handlers:
    debug_console_handler:
      level: INFO
      class: logging.StreamHandler
      formatter: brief
      stream: ext://sys.stdout
    debug_file_handler:
      level: DEBUG
      class: logging.FileHandler
      formatter: default
      filename: /home/pi/config/test_rvc_debug_nd.log
      mode: w
    unhandled_file_handler:
      level: DEBUG
      class: logging.FileHandler
      formatter: time-only
      filename: /home/pi/config/test_unhandled_rvc_nd.log
      mode: w
    rvc_bus_trace_handler:
      level: DEBUG
      class: logging.FileHandler
      formatter: time-only
      filename: /home/pi/config/RVC_FULL_BUS_TRACE.log
      mode: w

  loggers: 
    '': # root logger
      handlers: 
        - debug_console_handler
        - debug_file_handler
      level: DEBUG
      propagate: False

    'unhandled_rvc':  # unhandled messages
      handlers:
        - unhandled_file_handler
      level: DEBUG
      propagate: False

    'rvc_bus_trace':  # all bus messages
      handlers:
        - rvc_bus_trace_handler
      level: DEBUG
      propagate: False

  formatters:
    brief:
      format: '%(message)s'
    time-only:
      format: '%(asctime)s   %(message)s'
      datefmt: '%d %H:%M:%S'
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

#
# External Plugins for device entity
#
plugins:
  paths:
    - /
#
# RV - floorplan
#
map: 
  - dgn: 1FFBD
    instance: 1
    group: '00000000'
    type: light
    instance_name: bedroom_light

  - dgn: 1FFBD
    instance: 2
    group: '00000000'
    type: light
    instance_name: main_light

  - dgn: 1FFBD
    instance: 8
    group: '00000000'
    type: light
    instance_name: awning_light

  - dgn: 1FF9C
    instance: 2
    type: temperature
    instance_name: bedroom_temp

  - dgn: 1FFB7
    instance: 0
    type: tank_level
    instance_name: fresh_water_tank

  - dgn: 1FFB7
    instance: 1
    type: tank_level
    instance_name: black_waste_tank

  - dgn: 1FFB7
    instance: 2
    type: tank_level
    instance_name: rear_gray_waste_tank

  - dgn: 1FFB7
    instance: 18
    type: tank_level
    instance_name: galley_gray_waste_tank

  - name: WATER_PUMP_STATUS
    type: water_pump
    instance_name: fresh water pump

  - name: WATERHEATER_STATUS
    type: waterheater
    instance: 1
    instance_name: trailer waterheater

  - name: DC_LOAD_STATUS
    type: tank_warmer
    instance: 34
    instance_name: waste tank heater

  - name: DC_LOAD_STATUS
    type: tank_warmer
    instance: 35
    instance_name: fresh water tank heater






#
# MQTT specific settings
#
mqtt:
  broker:   100.64.39.110:9883
  username: rvc
  password: c0ugar
  